version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the website
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync . s3://your-bucket-name --delete
artifacts:
  files:
    - '**/*'
